### ISSUE TITLE
Licensing question.

### ISSUE THREAD

**Issue by datadams** [cfloutier/Unity-VNC-Client#4]
Hi cfloutier, I was wondering what kind of licensing is required to use this repo for a project.

**Comment by cfloutier** [comment]
Hello
It is totally open. No licences.

**Comment by datadams** [comment]
Thank you for clarification.

**Comment by datadams** [comment]
Would it be possible for me to use this in a commercial application?

**Comment by cfloutier** [comment]
it depends on the licence of the original repo. 
as VncSharp is GPL (lite)
you can clearly us it in any situation without restriction

**Comment by cfloutier** [comment]
I've added a licence file (LGPL) to clarify the situation
