### ISSUE TITLE
Upgrade to Unity 2020 LTS

### ISSUE THREAD

**Issue by jasonlmassey** [cfloutier/Unity-VNC-Client#8]
As a developer I want to upgrade to Unity 2020 Long-Term Support (LTS), so I can set up continuous integration.  

**Acceptance Criteria**
* code base builds with Unity2020.3.20f1LTS.  https://download.unity3d.com/download_unity/41c4e627c95f/UnityDownloadAssistant-2020.3.20f1.exe  
* build passes manual tests.

**Comment by SinanAkkoyun** [comment]
Thanks for the good work on the seemingly only Unity VNC out there!
